# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 14:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20160316_2151'),
    ]

    operations = [
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('withdrawal_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WithdrawalPurpose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.AlterField(
            model_name='meeting',
            name='participants',
            field=models.ManyToManyField(blank=True, to='contacts.Contact'),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='purpose',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contacts.WithdrawalPurpose'),
        ),
    ]
