# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-11 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20160310_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
